server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: false
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: employeeServiceCircuitBreaker
                fallbackUri: forward:/fallback/employee
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: unrestricted

resilience4j:
  circuitbreaker:
    instances:
      employeeServiceCircuitBreaker:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

jwt:
  secret-key: 1234567890123456789012345678901234567890123456789012345678901234
