server:
  port: 8888

spring:
  application:
    name: config-server

cloud:
  config:
    server:
      git:
        uri: https://github.com/arul1976/microservice-config
        clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

